<?php
namespace KSEO\SEO_Booster\Module;

/**
 * Robots Module for KE SEO Booster Pro
 * 
 * @package KSEO\SEO_Booster\Module
 */

/**
 * Robots Class
 * 
 * @since 2.0.0
 */
class Robots {
    
    /**
     * Initialize the robots module
     */
    public function __construct() {
        add_action('init', array($this, 'add_rewrite_rules'));
        add_action('template_redirect', array($this, 'handle_robots_request'));
    }
    
    /**
     * Add rewrite rules for robots.txt
     */
    public function add_rewrite_rules() {
        add_rewrite_rule('robots\.txt$', 'index.php?kseo_robots=1', 'top');
    }
    
    /**
     * Handle robots.txt requests
     */
    public function handle_robots_request() {
        if (get_query_var('kseo_robots')) {
            $this->output_robots();
            exit;
        }
    }
    
    /**
     * Generate robots.txt
     */
    public function generate() {
        $robots = $this->build_robots_content();
        return $robots;
    }
    
    /**
     * Output robots.txt
     */
    private function output_robots() {
        header('Content-Type: text/plain; charset=utf-8');
        
        $robots = $this->build_robots_content();
        echo $robots;
    }
    
    /**
     * Build robots.txt content
     */
    private function build_robots_content() {
        $content = "# Robots.txt generated by KE SEO Booster Pro\n";
        $content .= "# " . date('Y-m-d H:i:s') . "\n\n";
        
        // User-agent rules
        $content .= "User-agent: *\n";
        
        // Allow/disallow rules
        $disallow_rules = array(
            '/wp-admin/',
            '/wp-includes/',
            '/wp-content/plugins/',
            '/wp-content/themes/',
            '/wp-content/uploads/',
            '/wp-json/',
            '/search/',
            '/?s=',
            '/feed/',
            '/rss/',
            '/trackback/',
            '/page/',
            '/comments/',
            '/author/',
            '/tag/',
            '/category/',
            '/date/',
            '/attachment/'
        );
        
        foreach ($disallow_rules as $rule) {
            $content .= "Disallow: " . $rule . "\n";
        }
        
        // Allow specific directories
        $allow_rules = array(
            '/wp-content/uploads/',
            '/wp-content/themes/',
            '/wp-content/plugins/'
        );
        
        foreach ($allow_rules as $rule) {
            $content .= "Allow: " . $rule . "\n";
        }
        
        // Sitemap
        $content .= "\nSitemap: " . home_url('/sitemap.xml') . "\n";
        
        // Additional sitemaps
        $content .= "Sitemap: " . home_url('/sitemap-posts.xml') . "\n";
        $content .= "Sitemap: " . home_url('/sitemap-pages.xml') . "\n";
        $content .= "Sitemap: " . home_url('/sitemap-categories.xml') . "\n";
        $content .= "Sitemap: " . home_url('/sitemap-tags.xml') . "\n";
        
        // Crawl delay (optional)
        $crawl_delay = get_option('kseo_crawl_delay', '');
        if (!empty($crawl_delay)) {
            $content .= "\nCrawl-delay: " . intval($crawl_delay) . "\n";
        }
        
        return $content;
    }
    
    /**
     * Get cached robots.txt
     */
    private function get_cached_robots() {
        return get_transient('kseo_robots_cache');
    }
    
    /**
     * Cache robots.txt
     */
    private function cache_robots($robots) {
        set_transient('kseo_robots_cache', $robots, DAY_IN_SECONDS);
    }
    
    /**
     * Invalidate robots.txt cache
     */
    public function invalidate_cache() {
        delete_transient('kseo_robots_cache');
    }
} 